music/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
app_name='music'
urlpatterns=[
	url(r'^$',views.Index.as_view(),name='index'),
	url(r'^login/$',login,{'template_name':'music/signup.html'}),
	url(r'^register/$',views.save,name='save'),
	url(r'^(?P<pk>[0-9]+)/$',views.Detail.as_view(),name='detail'),
	url(r'album/create/$',views.Create.as_view(),name='album-create'),
	url(r'album/(?P<pk>[0-9]+)/update/$',views.Update.as_view(),name='album-update'),
	url(r'album/(?P<pk>[0-9]+)/delete/$',views.Delete.as_view(),name='album-delete'),
	url(r'album/(?P<pk>[0-9]+)/$',views.AddSong.as_view(),name='song-add'),
	url(r'album/(?P<album_id>[0-9]+)/song/(?P<song_id>[0-9]+)/$',views.song_delete,name='song-delete'),
	url(r'^songs/', views.SongList.as_view(), name='songs'),
	url(r'^album/videos/(?P<pk>[0-9]+)/delete/$',views.Deletev.as_view(),name='video-delete'),
	url(r'^album/documents/$', views.Doc.as_view(), name='docs'),
	url(r'^album/videos/$', views.Video.as_view(), name='create'),
	url(r'^album/documents/(?P<pk>[0-9]+)/delete/$',views.DeleteDoc.as_view(),name='doc-delete'),
	
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^music/',include("music.urls")),
]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models

from django.core.urlresolvers import reverse
class Album(models.Model):
	
	artist=models.CharField(max_length=250)
	album_title=models.CharField(max_length=250)
	
	album_logo=models.FileField()

	def get_absolute_url(self):       #It creates autopath for whatever album clicked to its detail page
		return reverse('music:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.artist+'-'+self.album_title

class song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	song_title=models.CharField(max_length=250)
	file_type=models.FileField(null=True)

	def __str__(self):
		return self.song_title

class video(models.Model):
	
	artist=models.CharField(max_length=250)
	video_title=models.CharField(max_length=250)
	video_logo=models.FileField()
	
	def get_absolute_url(self):       #It creates autopath for whatever album clicked to its detail page
		return reverse('music:detailv', kwargs={'pk':self.pk})

	def __str__(self):
		return self.artist+'-'+self.video_title

class document(models.Model):
	document_title=models.CharField(max_length=250)
	doc_url=models.FileField()

	def __str__(self):
		return self.document_title

music/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
        	model = User
		fields = ['username', 'email', 'password']

music/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album,song,video,document
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserCreateForm


'''def index(request):
	all_albums=Album.objects.all()
	context={'all_albums':all_albums}
	return render(request,'music/index.html',context)


def detail(request,album_id):
	album=get_object_or_404(Album,pk=album_id)
	return render(request,'music/detail.html',{'album':album})
'''
class Index(ListView):
	template_name='music/index.html'
	context_object_name='all_albums'
	def get_queryset(self):
		return Album.objects.all()

class Detail(DetailView):
	model=Album
	template_name='music/detail.html'

class Create(CreateView):
	model=Album
	template_name='music/create.html'
	fields=['artist','album_title','album_logo']

class Update(UpdateView):
	model=Album
	template_name='music/create.html'
	fields=['artist','album_title','album_logo']

class Delete(DeleteView):
	model=Album
	success_url=reverse_lazy('music:index')

class AddSong(CreateView):
	model=song
	template_name='music/songs.html'
	fields=['album','song_title','file_type']
	success_url='/music/'

def song_delete(request, album_id, song_id):
	album = get_object_or_404(Album, pk=album_id)
	song1 = song.objects.get(pk=song_id)
	song1.delete()
	return render(request, 'music/detail.html', {'album': album})

class SongList(ListView):
	model=Album
	context_object_name='all_albums'
	template_name='music/songlist.html'
	

class Video(CreateView,ListView):
	model=video
	context_object_name='all_video'
	template_name='music/vcreate.html'
	fields=['artist','video_title','video_logo']
	success_url=reverse_lazy('music:create')

class VideoList(ListView):
	model=video
	context_object_name='all_video'
	template_name='music/videolist.html'

class Doc(CreateView,ListView):
	model=document
	context_object_name='all_doc'
	template_name='music/document.html'
	fields=['document_title','doc_url']
	success_url=reverse_lazy('music:docs')

def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

def logout_user(request):
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		"form": form,
    		}
	return render(request, 'music/login.html', context)
 
class Deletev(DeleteView):
	model=video
	success_url=reverse_lazy('music:create')

class DeleteDoc(DeleteView):
	model=document
	success_url=reverse_lazy('music:docs')
	

music/templates/music/create.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}active{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 ">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="col-sm-12">
							<h2>Create/Update New Album</h2>
						</div>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{%for field in form %}
							<div class="form-group">
								<label class="control-label col-sm-2">{{field.label_tag}}</label>
								<div class="col-sm-10">{{field}}</div>
				
							</div>
						{% endfor %}<div class="col-sm-offset-2">
							<button type="submit" class="btn btn-success">Create</button></div>
						</form>
					</div>
				<div>
			</div>
		</div>
	</div>
{% endblock %}

music/templates/music/detail.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block active %} active{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-4 col-lg-3" >
				<div class="thumbnail">
					<a href="{% url 'music:detail' album.id%}">
						<img src="{{ album.album_logo.url}}" class="img-responsive"></a>
						<h3>{{album.album_title}}</h3>
						<h2>{{album.artist}}</h2>
				</div>
			</div>
			<div class="col-sm-8 col-lg-9">
				<ul class="nav nav-pills">
					<li class="active"><a href="" >View Songs</a><li>
					<li><a href="{% url 'music:song-add' album.id %}" class="glyphicon glyphicon-plus" >AddSong</a></li>
				</ul>
				<div class="panel panel-default" style="margin-top:10px">
					<div class="panel-body">
						
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Title</th>
										<th>File</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									{% for song in album.song_set.all%}
										<tr>
											<td>{{ song.song_title }}</td>
											<td>
										<a target="_blank" href="{{song.file_type.url}}">
<button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-play">&nbsp;play</span></button></a>
											</td>
											<td>
										<form action="{% url 'music:song-delete' album.id song.id %}" method="post" style="display:inline;">
									{% csrf_token %}  <!-- prevents cross-site forgery-->
									<input type="hidden" name="sid" value="{{song.id}}">
									<button type="submit" class="btn btn-danger btn-xs">
									<span class="glyphicon glyphicon-remove">&nbsp;Delete</span>
									</button>
								</form></td>
								</tbody>
									{% endfor %}		
							</table>
					</div>
				</div>
			</div>
		</div>
	</div>
				
				
{% endblock %}

music/templates/music/document.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}{{active}}{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 ">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="col-sm-12">
							<h2>Add New Document</h2>
						</div>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{%for field in form %}
							<div class="form-group">
								<label class="control-label col-sm-2">{{field.label_tag}}</label>
								<div class="col-sm-10">{{field}}</div>
				
							</div>
						{% endfor %}<div class="col-sm-offset-2">
							<button type="submit" class="btn btn-success">Add</button></div>
						</form>
					</div>
				<div>
			</div>
		</div>
	</div>


<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12"><h2>All Documents</h2></div>
			<div class="col-sm-12">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Title</th>
							<th>Document</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
					{% for doc1 in all_doc %}
						<tr>
							<td>{{doc1.document_title}}</td>
							
							<td><a target="_blank" href="{{doc1.doc_url}}">
<button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-play">&nbsp;show</span></button></a></td>
							<td><form action="{% url 'music:doc-delete' doc1.id%}" method="post" style="display:inline;">
									{% csrf_token %}  <!-- prevents cross-site forgery-->
									<input type="hidden" name="sid" value="{{doc1.id}}">
									<button type="submit" class="btn btn-danger btn-xs">
									<span class="glyphicon glyphicon-remove">&nbsp;Delete</span>
									</button>
								</form></td>
						</tr>
					{% endfor %}
					</tbody>

				</table>
				
			</div>
		</div>
	</div>
{% endblock %}

music/templates/music/genre.html
<!DOCTYPE html>
<head>
<title>{% block title%}Tuber{% endblock%}</title>


{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
</body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lol">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{%url 'music:index'%}">Tuber</a>
		</div>
		<div class="collapse navbar-collapse" id="lol">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'music:index'%}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Album
					</a>
				<li>
				<li class="">
					<a href="{% url 'music:songs' %}">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
					</a>
				<li>
				<li class="">
					<a href="{% url 'music:create' %}">
						<span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;Videos
					</a>
				<li>
				<li class="">
					<a href="{% url 'music:docs' %}">
						<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>&nbsp;Documents
					</a>
				<li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-create'%}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add album
					</a>
				<li>
				<li class="">
					<a href="">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
					</a>
				<li>
			</ul>

	</div>

</nav>
{% block body%}
{% endblock%}
</body>
</html>

music/templates/music/index.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}active{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12">
				<h2>Albums</h2>
			</div>
			{% if all_albums %}
				{% for album in all_albums%}
					<div class="col-sm-4 col-lg-3" >
						<div class="thumbnail">
							<a href="{% url 'music:detail' album.id %}" "><img src="{{ album.album_logo.url}}" class="img-responsive" ></a>
							<div class="caption">
								<h2>{{ album.album_title }}</h2>
								<h3>{{ album.artist}}</h3>
								<a href="{% url 'music:detail' album.id%}" class='btn btn-default'>View Details</a>
								<form action="{% url 'music:album-delete' album.id%}" method="post" style="display:inline;">
									{% csrf_token %}  <!-- prevents cross-site forgery-->
									<input type="hidden" name="sid" value="{{album.id}}">
									<button type="submit" class="btn btn-default">
									<span class="glyphicon glyphicon-trash"></span>
									</button>
								</form>
								<a href="{% url 'music:album-update' album.id%}" class='btn btn-default'>Edit</a>
							</div>
						</div>
					</div>
				{% endfor%}
			{% endif%}
		</div>
	</div>
	
	  
{% endblock %}

music/templates/music/signup.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
</body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lol">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Tuber</a>
		</div>
		<div class="collapse navbar-collapse" id="lol">
			
				
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:save' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Register
					</a>
				<li>
				<li class="">
					<a href="/music/login">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Login
					</a>
				<li>
			</ul>

	</div>

</nav>


	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 ">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="col-sm-12">
							<h2>Login</h2>
						</div>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{%for field in form %}
							<div class="form-group">
								<label class="control-label col-sm-2">{{field.label_tag}}</label>
								<div class="col-sm-10">{{field}}</div>
				
							</div>
						{% endfor %}<div class="col-sm-offset-2">
							<button type="submit" class="btn btn-success">Submit</button></div>
						</form>
					</div>
				<div>
			</div>
		</div>
	</div>

music/templates/music/songlist.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}active{% endblock%}
{% block body%}
<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12"><h2>All Songs</h2></div>
			<div class="col-sm-12">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Title</th>
							<th>Artist</th>
							<th>Song</th>
							<th>Album</th>
						</tr>
					</thead>
					<tbody>
					{% for album in all_albums %}<!-- I did it.-->
						
						{% for songs in album.song_set.all %}
							
							<tr>
							<td>{{songs.song_title}}</td>
							<td>{{songs.album.artist}}</td>
							<td><a target="_blank" href="{{songs.file_type.url}}">
<button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-play">&nbsp;play</span></button></a></td>
							<td>{{songs.album.album_title}}</td>
							</tr>
						{% endfor %}
					{% endfor %}
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}active{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 ">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="col-sm-12">
							<h2>Add New Song</h2>
						</div>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{%for field in form %}
							<div class="form-group">
								<label class="control-label col-sm-2">{{field.label_tag}}</label>
								<div class="col-sm-10">{{field}}</div>
				
							</div>
						{% endfor %}<div class="col-sm-offset-2">
							<button type="submit" class="btn btn-success">Submit</button></div>
						</form>
					</div>
				<div>
			</div>
		</div>
	</div>
{% endblock %}

music/templates/music/vcreate.html
{% extends 'music/genre.html'%}
{% block title%}{{album}}{%  endblock %}
{% block albums_active%}active{% endblock%}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 ">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="col-sm-12">
							<h2>Add New Video</h2>
						</div>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{%for field in form %}
							<div class="form-group">
								<label class="control-label col-sm-2">{{field.label_tag}}</label>
								<div class="col-sm-10">{{field}}</div>
				
							</div>
						{% endfor %}<div class="col-sm-offset-2">
							<button type="submit" class="btn btn-success">Submit</button></div>
						</form>
					</div>
				<div>
			</div>
		</div>
	</div>


<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12"><h2>All Videos</h2></div>
			<div class="col-sm-12">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Title</th>
							<th>Artist</th>
							<th>video</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
					{% for video1 in all_video %}
						<tr>
							<td>{{video1.video_title}}</td>
							<td>{{video1.artist}}</td>
							<td><a target="_blank" href="{{video1.video_logo.url}}">
<button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-play">&nbsp;play</span></button></a></td>
							<td><form action="{% url 'music:video-delete' video1.id%}" method="post" style="display:inline;">
									{% csrf_token %}  <!-- prevents cross-site forgery-->
									<input type="hidden" name="sid" value="{{video1.id}}">
									<button type="submit" class="btn btn-danger btn-xs">
									<span class="glyphicon glyphicon-remove">&nbsp;Delete</span>
									</button>
								</form></td>
						</tr>
					{% endfor %}
					</tbody>

				</table>
				
			</div>
		</div>
	</div>
{% endblock %}